import json
import os
from contextlib import contextmanager
from datetime import datetime, timezone
from functools import lru_cache
from typing import Any, Iterator

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection, Row

from .config import get_settings


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


@lru_cache
def get_engine():
    settings = get_settings()
    if settings.database_url.startswith("sqlite"):
        os.makedirs(os.path.dirname(settings.database_path), exist_ok=True)
    return create_engine(settings.database_url, pool_pre_ping=True, future=True)


def init_db() -> None:
    schema = """
    create table if not exists documents (
        id integer generated by default as identity primary key,
        filename text not null,
        file_type text not null,
        path text not null,
        status text not null default 'uploaded',
        error_message text not null default '',
        chunk_count integer not null default 0,
        indexed_at text,
        created_at text not null
    );

    create table if not exists chunks (
        id text primary key,
        document_id integer not null references documents(id) on delete cascade,
        chunk_index integer not null,
        text text not null,
        metadata_json text not null,
        created_at text not null
    );

    create table if not exists conversations (
        id text primary key,
        title text not null,
        created_at text not null
    );

    create table if not exists messages (
        id text primary key,
        conversation_id text not null references conversations(id) on delete cascade,
        question text not null,
        answer text not null,
        sources_json text not null,
        latency_ms integer not null,
        created_at text not null
    );

    create table if not exists feedback (
        id integer generated by default as identity primary key,
        message_id text not null references messages(id) on delete cascade,
        rating text not null,
        comment text not null default '',
        created_at text not null
    );

    create table if not exists app_config (
        key text primary key,
        value text not null
    );
    """
    with get_engine().begin() as conn:
        for statement in schema.split(";"):
            if statement.strip():
                conn.execute(text(statement))


@contextmanager
def db() -> Iterator[Connection]:
    with get_engine().begin() as conn:
        yield conn


def row_to_dict(row: Row | Any) -> dict[str, Any]:
    if hasattr(row, "_mapping"):
        return dict(row._mapping)
    return dict(row)


def get_runtime_config() -> dict[str, Any]:
    settings = get_settings()
    defaults: dict[str, Any] = {
        "chunk_size": settings.default_chunk_size,
        "chunk_overlap": settings.default_chunk_overlap,
        "top_k": settings.default_top_k,
        "rerank": settings.default_rerank,
        "min_score": settings.default_min_score,
        "llm_provider": settings.llm_provider,
        "chat_model": settings.chat_model,
        "embedding_provider": settings.embedding_provider,
        "embedding_model": settings.embedding_model,
        "embedding_dimensions": settings.embedding_dimensions,
        "vector_candidate_multiplier": settings.vector_candidate_multiplier,
        "hybrid_vector_weight": settings.hybrid_vector_weight,
        "hybrid_bm25_weight": settings.hybrid_bm25_weight,
        "bm25_k1": settings.bm25_k1,
        "bm25_b": settings.bm25_b,
        "rerank_original_score_weight": settings.rerank_original_score_weight,
        "rerank_term_coverage_weight": settings.rerank_term_coverage_weight,
        "rerank_provider": settings.rerank_provider,
        "rerank_base_url": settings.rerank_base_url,
        "rerank_model": settings.rerank_model,
        "rerank_timeout_seconds": settings.rerank_timeout_seconds,
        "local_answer_min_score": settings.local_answer_min_score,
        "local_answer_relative_score": settings.local_answer_relative_score,
        "local_answer_max_contexts": settings.local_answer_max_contexts,
        "local_answer_snippet_length": settings.local_answer_snippet_length,
        "conversation_history_limit": settings.conversation_history_limit,
        "conversation_title_length": settings.conversation_title_length,
        "error_message_max_length": settings.error_message_max_length,
        "dedupe_key_length": settings.dedupe_key_length,
        "llm_timeout_seconds": settings.llm_timeout_seconds,
        "llm_temperature": settings.llm_temperature,
        "embedding_timeout_seconds": settings.embedding_timeout_seconds,
    }
    with db() as conn:
        rows = conn.execute(text("select key, value from app_config")).mappings().fetchall()
    config = defaults.copy()
    for row in rows:
        config[row["key"]] = json.loads(row["value"])
    return config


def update_runtime_config(payload: dict[str, Any]) -> dict[str, Any]:
    allowed = {
        "chunk_size",
        "chunk_overlap",
        "top_k",
        "rerank",
        "min_score",
        "llm_provider",
        "chat_model",
        "embedding_provider",
        "embedding_model",
        "embedding_dimensions",
        "vector_candidate_multiplier",
        "hybrid_vector_weight",
        "hybrid_bm25_weight",
        "bm25_k1",
        "bm25_b",
        "rerank_original_score_weight",
        "rerank_term_coverage_weight",
        "rerank_provider",
        "rerank_base_url",
        "rerank_model",
        "rerank_timeout_seconds",
        "local_answer_min_score",
        "local_answer_relative_score",
        "local_answer_max_contexts",
        "local_answer_snippet_length",
        "conversation_history_limit",
        "conversation_title_length",
        "error_message_max_length",
        "dedupe_key_length",
        "llm_timeout_seconds",
        "llm_temperature",
        "embedding_timeout_seconds",
    }
    with db() as conn:
        for key, value in payload.items():
            if key in allowed:
                conn.execute(
                    text(
                        "insert into app_config(key, value) values(:key, :value) "
                        "on conflict(key) do update set value = excluded.value"
                    ),
                    {"key": key, "value": json.dumps(value, ensure_ascii=False)},
                )
    return get_runtime_config()
