"""access control and audit logs

Revision ID: 0004_access_control_audit
Revises: 0003_document_processing_status
Create Date: 2026-05-13
"""

from alembic import op


revision = "0004_access_control_audit"
down_revision = "0003_document_processing_status"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        create table if not exists departments (
            id integer generated by default as identity primary key,
            name text not null,
            created_at text not null
        )
        """
    )
    op.execute(
        """
        create table if not exists users (
            id text primary key,
            username text,
            password_hash text,
            name text not null,
            role text not null default 'user',
            department_id integer references departments(id),
            position_id integer,
            status text not null default 'active',
            last_login_at text,
            created_at text not null
        )
        """
    )
    op.execute("create unique index if not exists idx_users_username on users(username) where username is not null")
    op.execute(
        """
        create table if not exists positions (
            id integer generated by default as identity primary key,
            name text not null,
            department_id integer references departments(id),
            description text not null default '',
            created_at text not null
        )
        """
    )
    op.execute(
        """
        create table if not exists roles (
            id integer generated by default as identity primary key,
            code text not null unique,
            name text not null,
            description text not null default '',
            created_at text not null
        )
        """
    )
    op.execute(
        """
        create table if not exists permissions (
            id integer generated by default as identity primary key,
            code text not null unique,
            name text not null,
            description text not null default '',
            created_at text not null
        )
        """
    )
    op.execute(
        """
        create table if not exists user_roles (
            user_id text not null references users(id) on delete cascade,
            role_id integer not null references roles(id) on delete cascade,
            primary key(user_id, role_id)
        )
        """
    )
    op.execute(
        """
        create table if not exists role_permissions (
            role_id integer not null references roles(id) on delete cascade,
            permission_id integer not null references permissions(id) on delete cascade,
            primary key(role_id, permission_id)
        )
        """
    )
    op.execute(
        """
        create table if not exists audit_logs (
            id integer generated by default as identity primary key,
            actor_user_id text not null,
            action text not null,
            resource_type text not null,
            resource_id text not null,
            detail_json text not null default '{}',
            created_at text not null
        )
        """
    )

    op.execute("alter table documents add column if not exists department_id integer references departments(id)")
    op.execute("alter table documents add column if not exists uploaded_by text")
    op.execute("alter table documents add column if not exists visibility text not null default 'department'")
    op.execute("alter table messages add column if not exists user_id text")
    op.execute("alter table users add column if not exists username text")
    op.execute("alter table users add column if not exists password_hash text")
    op.execute("alter table users add column if not exists position_id integer")
    op.execute("alter table users add column if not exists status text not null default 'active'")
    op.execute("alter table users add column if not exists last_login_at text")

    op.execute("comment on table departments is '部门表，用于企业知识库隔离'")
    op.execute("comment on table users is '用户表，保存登录账号、密码哈希、角色和所属部门'")
    op.execute("comment on table positions is '岗位表，保存用户岗位信息'")
    op.execute("comment on table roles is '角色表，保存系统角色'")
    op.execute("comment on table permissions is '权限表，保存接口和功能权限'")
    op.execute("comment on table user_roles is '用户角色关联表'")
    op.execute("comment on table role_permissions is '角色权限关联表'")
    op.execute("comment on table audit_logs is '审计日志表，记录关键操作'")
    op.execute("comment on column documents.department_id is '文档所属部门 ID'")
    op.execute("comment on column documents.uploaded_by is '上传用户 ID'")
    op.execute("comment on column documents.visibility is '文档可见范围：public、department、private'")
    op.execute("comment on column messages.user_id is '发起问答的用户 ID'")


def downgrade() -> None:
    op.execute("alter table messages drop column if exists user_id")
    op.execute("alter table documents drop column if exists visibility")
    op.execute("alter table documents drop column if exists uploaded_by")
    op.execute("alter table documents drop column if exists department_id")
    op.execute("drop table if exists role_permissions")
    op.execute("drop table if exists user_roles")
    op.execute("drop table if exists permissions")
    op.execute("drop table if exists roles")
    op.execute("drop table if exists positions")
    op.execute("drop table if exists audit_logs")
    op.execute("drop index if exists idx_users_username")
    op.execute("drop table if exists users")
    op.execute("drop table if exists departments")
